spring:
    application:
        name: drdarwin
    ai:
        ollama:
            base-url: http://localhost:11434
            chat:
                model: deepseek-r1:7b
    data:
        mongodb:
            host: localhost
            database: doctordarwin
            port: 27017
#            username: <your_username>
#            password: <your_password>

server:
    port: 8080
